### ISSUE TITLE
transitive dependency on hitimes gem 1.x can produce a LoadError

### ISSUE THREAD

**Issue by eli-darkly** [launchdarkly/ruby-eventsource#6]
This was mentioned in [a comment](https://github.com/launchdarkly/ruby-server-sdk/issues/155#issuecomment-620252100) on a Ruby SDK issue filed by @camillof. Currently, the Ruby SSE implementation uses [Socketry](https://github.com/socketry/socketry) to implement read timeouts on streaming connections. Socketry uses an old version of [`hitimes`](https://github.com/copiousfreetime/hitimes), which apparently in some environments can cause this error:

```
/usr/local/DFS/gems/hitimes-1.3.1/lib/hitimes.rb:56:in `<top (required)>': Unable to find binary extension, was hitimes installed correctly? The following paths were tried. (LoadError)
/Users/camillo/hitimes/2.6/hitimes : incompatible library version - /usr/local/DFS/gems/hitimes-1.3.1/lib/hitimes/2.6/hitimes.bundle
/Users/camillo/hitimes/hitimes : cannot load such file -- hitimes/hitimes
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/DFS/gems/socketry-0.5.1/lib/socketry.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/DFS/gems/ld-eventsource-1.0.3/lib/ld-eventsource/impl/streaming_http.rb:5:in `<top (required)>'
```

The 2.0 release of `hitimes` seems to fix this. However, Socketry is unmaintained so a patch to use this update may not become available. Options would include forking Socketry or pursuing a different strategy to implement timeouts.

**Comment by eli-darkly** [comment]
This is obsolete since, as of v2.0.0 of our gem, we are no longer using Socketry.
